// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYBT51gUGrROBkj-ONjQc3lWJjyu7gX1M',
    appId: '1:896672766195:android:ea33d2a2c40a482a81ff86',
    messagingSenderId: '896672766195',
    projectId: 'flutter-database-f6af4',
    databaseURL: 'https://flutter-database-f6af4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-database-f6af4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn3px5_RQnVg4c3Tm5pp26rSB1m6e5hqI',
    appId: '1:896672766195:ios:36927761861bedbd81ff86',
    messagingSenderId: '896672766195',
    projectId: 'flutter-database-f6af4',
    databaseURL: 'https://flutter-database-f6af4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-database-f6af4.firebasestorage.app',
    androidClientId: '896672766195-641k6ppgufc394d5qn5d0ebb0nn84qjk.apps.googleusercontent.com',
    iosClientId: '896672766195-p9t2r3tsof6nlc92uera15it72hnhtra.apps.googleusercontent.com',
    iosBundleId: 'com.example.belajarCiCd',
  );
}
